### ISSUE TITLE
Hello, need help about Signal

### ISSUE THREAD

**Issue by TVHstudio** [adityaasoleh/Hello-Earth#1]
Hello, can you guide me how to setup the server, 
I can pay for help.
Please share me your contact

**Comment by adityaasoleh** [comment]
Hi, sure, write me at adityaasoleh@cryptnet.co.id :)

**Comment by adityaasoleh** [comment]
> Hello, can you guide me how to setup the server, I can pay for help. Please share me your contact

Hi, sure, write me at adityaasoleh@cryptnet.co.id :)
